# Generated by Django 6.0.3 on 2026-04-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_skill_title_remove_skill_user_skill_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skill_images/'),
        ),
    ]
